services:
  fcp-sfd-frontend:
    build:
      context: ../../fcp-sfd-frontend
      target: development
    image: fcp-sfd-frontend-development
    container_name: fcp-sfd-frontend-development
    ports:
      - "3002:3002"
    links:
      - "localstack:localstack"
      - "redis:redis"
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
    volumes:
      - ../../fcp-sfd-frontend/src:/home/node/src
      - ../../fcp-sfd-frontend/package.json:/home/node/package.json
    env_file:
      - ../.env
    environment:
      PORT: 3002
      NODE_ENV: development
      LOCALSTACK_ENDPOINT: http://localstack:4566
    networks:
      - fcp-sfd
