services:
  fcp-sfd-comms:
    build:
      context: ../../fcp-sfd-comms
      target: development
    image: fcp-sfd-comms-development
    container_name: fcp-sfd-comms-development
    ports:
      - '3001:3001'
    links:
      - 'localstack:localstack'
      - 'mongodb:mongodb'
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
    volumes:
      - ../../fcp-sfd-comms/src:/home/node/src
      - ../../fcp-sfd-comms/package.json:/home/node/package.json
    env_file:
      - ../.env
    environment:
      PORT: 3001
      NODE_ENV: development
      MONGO_URI: mongodb://mongodb:27017/
      SQS_ENDPOINT: http://localstack:4566
      COMMS_REQUEST_QUEUE_URL: http://sqs.eu-west-2.127.0.0.1:4566/000000000000/fcp_sfd_comms_request
      COMMS_REQUEST_DEAD_LETTER_QUEUE_URL: http://sqs.eu-west-2.127.0.0.1:4566/000000000000/fcp_sfd_comms_request-deadletter
      SNS_ENDPOINT: http://localstack:4566
      COMM_EVENTS_TOPIC_ARN: arn:aws:sns:eu-west-2:000000000000:fcp_sfd_comm_events
      FDM_QUEUE_URL: http://sqs.eu-west-2.127.0.0.1:4566/000000000000/fcp_fdm_events
      NOTIFY_API_KEY: ${NOTIFY_API_KEY}
    networks:
      - fcp-sfd
